//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSite_CuaHangBanHangDienThoaiDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ProductDetailMemory
    {
        public int ProductDetailMemoryId { get; set; }
        public Nullable<int> Ram { get; set; }
        public string DungLuong { get; set; }
        public Nullable<int> ProductDetaiId { get; set; }
    
        public virtual tb_ProductDetai tb_ProductDetai { get; set; }
    }
}
