//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSite_CuaHangBanHangDienThoaiDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ProductDetai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_ProductDetai()
        {
            this.tb_CartItem = new HashSet<tb_CartItem>();
            this.tb_OrderDetail = new HashSet<tb_OrderDetail>();
            this.tb_ProductDetailConnect = new HashSet<tb_ProductDetailConnect>();
            this.tb_ProductDetailMemory = new HashSet<tb_ProductDetailMemory>();
            this.tb_ProductDetailPin = new HashSet<tb_ProductDetailPin>();
            this.tb_ProductDetailProcessor = new HashSet<tb_ProductDetailProcessor>();
            this.tb_ProductImage = new HashSet<tb_ProductImage>();
            this.tb_ReturnDetail = new HashSet<tb_ReturnDetail>();
            this.tb_Review = new HashSet<tb_Review>();
        }
    
        public int ProductDetaiId { get; set; }
        public string Title { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Modifeby { get; set; }
        public string Alias { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsHome { get; set; }
        public Nullable<bool> IsSale { get; set; }
        public Nullable<bool> IsFeature { get; set; }
        public Nullable<bool> IsHot { get; set; }
        public string SeoTitle { get; set; }
        public string SeoDescription { get; set; }
        public string ProductCode { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PriceSale { get; set; }
        public Nullable<decimal> OrigianlPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> Color { get; set; }
        public Nullable<bool> TypeProduct { get; set; }
        public Nullable<int> ProductCategoryId { get; set; }
        public Nullable<int> ProductCompanyId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_CartItem> tb_CartItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_OrderDetail> tb_OrderDetail { get; set; }
        public virtual tb_ProductCategory tb_ProductCategory { get; set; }
        public virtual tb_ProductCompany tb_ProductCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ProductDetailConnect> tb_ProductDetailConnect { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ProductDetailMemory> tb_ProductDetailMemory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ProductDetailPin> tb_ProductDetailPin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ProductDetailProcessor> tb_ProductDetailProcessor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ProductImage> tb_ProductImage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ReturnDetail> tb_ReturnDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Review> tb_Review { get; set; }
    }
}
