//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSite_CuaHangDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ProductDetailProcessor
    {
        public int ProductDetailProcessorId { get; set; }
        public string HeDieuHanh { get; set; }
        public string CPU { get; set; }
        public string TocDoCPU { get; set; }
        public string GPU { get; set; }
        public string TocDoGPU { get; set; }
        public Nullable<int> ProductDetaiId { get; set; }
    
        public virtual tb_ProductDetai tb_ProductDetai { get; set; }
    }
}
