//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSite_CuaHangBanHangDienThoaiDiDong.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ProductDetailConnect
    {
        public int ProductDetailConnectId { get; set; }
        public string MangDiDong { get; set; }
        public string Sim { get; set; }
        public string Wifi { get; set; }
        public string GPS { get; set; }
        public string Bluetooth { get; set; }
        public string CongKetNoi { get; set; }
        public string JackTaiNghe { get; set; }
        public Nullable<int> ProductDetaiId { get; set; }
    
        public virtual tb_ProductDetai tb_ProductDetai { get; set; }
    }
}
