//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSite_CuaHangDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ProductDetailPin
    {
        public int ProductDetailPinId { get; set; }
        public string DungLuongPin { get; set; }
        public string LoaiPin { get; set; }
        public string HoTroSac { get; set; }
        public string CongNghePin { get; set; }
        public Nullable<int> ProductDetaiId { get; set; }
    
        public virtual tb_ProductDetail tb_ProductDetail { get; set; }
    }
}
